site_name: rraushan
site_url: https://rraushan.blog
site_description: What I do in my free time
site_author: Raushan
copyright: 2026 Raushan

theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  favicon: assets/logo.png
  font:
    text: DM Sans
    code: DM Mono
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tooltips
    - toc.follow
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - stylesheets/extra.js

plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - blog:
      blog_dir: .
      post_date_format: long
      post_url_format: "{date}/{slug}"
      authors: false
      archive: false
      categories: false
      post_excerpt: required

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
      title: On this page
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:mod.rakesh24@gmail.com
      name: Email
  analytics:
      provider: google
      property: G-2V1DQP2HE9

hooks:
  - overrides/hooks/views_badge.py
  - overrides/hooks/html_sections.py

